config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books do
    resources :readings
  end

  resources :authors, :authorships, :genres, :languages, :locations

  root to: 'books#index'

  match 'unread' => 'books#unread', :via => 'get'

  match 'lchart' => 'languages#languageschart', :via => 'get'
end

app/models/reading.rb
# frozen_string_literal: true

# Basic ActiveRecord model Nothing fancy.
class Reading < ApplicationRecord
  belongs_to :book

  def period
    date_started..date_finished
  end

end

app/controllers/readings_controller.rb
# frozen_string_literal: true

class ReadingsController < ApplicationController
  # GET /readings
  # GET /readings.xml
  def index
    @readings = Reading.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @readings }
    end
  end

  # GET /readings/1
  # GET /readings/1.xml
  def show
    @book = Book.find(params[:book_id])
    @reading = @book.readings.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render xml: @reading }
    end
  end

  # GET /books/1/readings/new
  # GET /books/1/readings/new.xml
  def new
    @book = Book.find(params[:book_id])
    @reading = Reading.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render xml: @reading }
    end
  end

  # GET /readings/1/edit
  def edit
    @book = Book.find(params[:book_id])
    @reading = @book.readings.find(params[:id])
  end

  # POST /readings
  # POST /readings.xml
  def create
    @book = Book.find(params[:book_id])
    @reading = @book.readings.new(reading_params)

    respond_to do |format|
      if @reading.save
        format.html { redirect_to(@book, notice: 'Reading was successfully created.') }
        format.xml  { render xml: @book, status: :created, location: @reading }
      else
        format.html { render action: 'new' }
        format.xml  { render xml: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /readings/1
  # PUT /readings/1.xml
  def update
    @book = Book.find(params[:book_id])
    @reading = @book.readings.find(params[:id])

    respond_to do |format|
      if @reading.update(reading_params)
        format.html { redirect_to(@book, notice: 'Reading was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render action: 'edit' }
        format.xml  { render xml: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /readings/1
  # DELETE /readings/1.xml
  def destroy
    @reading = Reading.find(params[:id])
    @reading.destroy

    respond_to do |format|
      format.html { redirect_to(readings_url) }
      format.xml  { head :ok }
    end
  end

  private

  def reading_params
    params.require(:reading).permit(
      :date_started,
      :date_finished,
      :rating,
      :comments
    )
  end
end

app/helpers/readings_helper.rb
# frozen_string_literal: true

module ReadingsHelper
  def markdown_parse(str)
    BlueCloth.new(str).to_html.html_safe
  end
end

app/views/readings/_form.html.haml
= form_for [@book, @reading] do |f|
  %p #{ f.label :rating, "Rating:"} #{ f.text_field :rating }
  %p #{ f.label :comments, "Comments:" }<br /> #{ f.text_area :comments }
  %p #{ f.label :date_started, "Date Started:" } #{ f.date_field 'date_started', :dateFormat => 'yy-mm-dd', :dataBehaviour => 'datepicker' }
  %p #{ f.label :date_finished, "Date Finished:" } #{ f.date_field 'date_finished', :dateFormat => 'yy-mm-dd', :dataBehaviour => 'datepicker' }
  %p #{ f.submit 'Create' }

app/views/readings/_show.html.haml
-@book.readings.each do |r|
  .reading
    %p Rating: #{r.rating}
    -if r.comments
      %p Comments: #{markdown_parse(r.comments)}
  
    %p Date Started: #{r.date_started} | Date Finished: #{r.date_finished} | Last Modified: #{r.updated_on}
    %p= link_to 'View this reading', book_reading_path(@book, r)

app/views/readings/edit.html.haml
%h1 Editing reading for <i>#{@book.title}</i>

=render 'form'

%p #{link_to 'Show', @book } | #{link_to 'Back', book_readings_path }

app/views/readings/index.html.haml
%h1 Listing of readings

%table
  %tr
    %th Book
    %th Rating
    %th Comments
    %th Date started
    %th Date finished
    %th Last modified
  

- @readings.each do |reading|
  %tr
    %td #{ reading.book_id }
    %td #{ reading.rating }
    %td #{ reading.comments }
    %td #{ reading.date_started }
    %td #{ reading.date_finished }
    %td #{ reading.updated_on }
    %td #{ link_to  'Show', book_reading_path }
    %td #{ link_to  'Edit', edit_book_reading_path(reading) }
    %td #{ link_to  'Destroy', reading, :confirm => 'Are you sure?', :method => :delete }

%p #{ link_to  'New reading', new_reading_path }

app/views/readings/new.html.haml
%h1 New reading for #{@book.title}
=@reading.errors
=render 'form'  
%p #{link_to 'Back', books_path }

app/views/readings/show.html.haml
%h1 Reading for:
%h2= link_to @book.title, book_path(@book)
%h3= link_to @book.authorships.first.author.fullname, author_path(@book.authorships.first.author)

%p Rating: #{@reading.rating}

%p Comments: #{ markdown_parse(@reading.comments) }

%p Date Started: #{@reading.date_started} | Date Finished: #{ @reading.date_finished } | Last Modified: #{ @reading.updated_on }

%p #{ link_to 'Edit', edit_book_reading_path}