config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books do
    resources :readings
  end

  resources :authors, :authorships, :genres, :languages, :locations

  root to: 'books#index'

  match 'unread' => 'books#unread', :via => 'get'

  match 'lchart' => 'languages#languageschart', :via => 'get'
end

app/models/author.rb
# frozen_string_literal: true

# Class to also include methods for sanitizing author names
# and collect stats for relating to authors
class Author < ApplicationRecord
  has_many :authorships
  has_many :books, through: :authorships
  has_one :biography
  before_save :process_author

  def fullname
    author_first + ' ' + author_last
  end

  def process_author
    self.name = "#{author_first} #{author_last}".strip
  end

  def self.find_most_prominent_authors
    query = <<-SQL
    select count(ap.author_id) as "total", a.name, a.id
    from authorships ap
    Inner Join authors a on ap.author_id = a.id
    group by ap.author_id
    order by total DESC limit 10
    SQL
    Author.find_by_sql(query)
  end

  def json_attributes
    { id: id, name: name }
  end
end

app/controllers/authors_controller.rb
# frozen_string_literal: true

class AuthorsController < ApplicationController
  # GET /authors
  # GET /authors.xml

  def index
    @authors = Author.where('name like ?', "%#{params[:q]}%").order(:author_last, :author_first)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @authors }
      format.json { render json: @authors.map(&:json_attributes) }
    end
  end

  # GET /authors/1
  # GET /authors/1.xml
  def show
    @author = Author.find(params[:id])
    @bio = Biography.fetch_bio(@author)
    @page_title = 'Details for ' + @author.name
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render xml: @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.xml
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render xml: @author }
      format.js
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.xml
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        flash[:notice] = 'Author was successfully created.'
        format.html { redirect_to(@author) }
        format.xml  { render xml: @author, status: :created, location: @author }
        format.js { render action: 'show' }
      else
        flash[:notice] = "Something's gone horribly wrong."
        format.html { render action: 'new' }
        format.xml  { render xml: @author.errors, status: :unprocessable_entity }
        format.js { render action: 'new' }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.xml
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update(author_params)
        flash[:notice] = 'Author was successfully updated.'
        format.html { redirect_to(@author) }
        format.xml  { head :ok }
      else
        format.html { render action: 'edit' }
        format.xml  { render xml: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.xml
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to(authors_url) }
      format.xml  { head :ok }
    end
  end

  private

  def author_params
    params.require(:author).permit(
      :author_first,
      :author_last
    )
  end
end

app/helpers/authors_helper.rb
# frozen_string_literal: true

module AuthorsHelper
end

app/views/authors/_author.html.haml
= form_for(@author) do |f|
  %p #{f.label :author_first} #{f.text_field :author_first}
  %p #{f.label :author_last} #{f.text_field :author_last}
  %p.smaller Include all details here exactly as they should be presented later. 
  %p #{f.submit 'Create'}

app/views/authors/_remoteauthor.html.haml
= form_for(@author, :remote => true) do |f|
  %p #{f.label :author_first} #{f.text_field :author_first}
  %p #{f.label :author_last} #{f.text_field :author_last}
  %p.smaller Include all details here exactly as they should be presented later. 
  %p #{f.submit 'Create'}

app/views/authors/edit.html.haml
%h1 Editing author

=render 'author'  
%p #{link_to 'Show', @author } | #{link_to 'Back', authors_path}

app/views/authors/index.haml
%h1 Listing authors

%table
	%tr
	-@authors.each do |author|
		%tr
			%td= author.name
			%td= link_to 'Show', author
			%td= link_to 'Edit', edit_author_path(author)
			%td= link_to 'Destroy', author, :confirm => 'Are you sure?', :method => :delete

%a= link_to 'New author', new_author_path

app/views/authors/index.html.haml
%h1 Listing authors

%table
	%tr
	-@authors.each do |author|
		%tr
			%td= author.name
			%td= link_to 'Show', author
			%td= link_to 'Edit', edit_author_path(author)
			
%a= link_to 'New author', new_author_path

app/views/authors/new.html.haml
%h1 New author
= @author.errors
=render 'author'
%p #{ link_to 'Back', authors_path }

app/views/authors/new.js.erb
$('#modal-receiver').html('<h2>New Author').append('<%= escape_javascript(render "remoteauthor") %> or <a class=\"close-modal\" href=\"#\"> Cancel</a>');

$('a.close-modal').click(
  function(){
    $('#modal-receiver').fadeOut('slow');
    $('#blackout').fadeOut('slow');
  });

app/views/authors/show.haml
%h2=@author.name

%h3 is the author of:
%ul
-@author.books.each do |book|
	%li= link_to book.title, book_path(book)

%a=link_to 'Edit', edit_author_path(@author)
%a= link_to 'Back', authors_path

app/views/authors/show.html.haml
%h2=@author.name

%div#book-list
  %h3 is the author of:
  %ul
  -@author.books.each do |book|
    %li= link_to book.title, book_path(book)

%div#bio-section
  %img{ :src=> @bio.main_image_url, :width => "200", :class => "author-portrait"} 
  =@bio.summary
  %p
    %a=link_to 'Read More', @bio.fullurl

#page-nav
  %a=link_to 'Edit', edit_author_path(@author)
  %a= link_to 'Back', authors_path

app/views/authors/show.js.erb
$('#modal-receiver').empty();
var contents = "<h2>Your author has been created.</h2>\n";
contents += "<p><%= escape_javascript(@author.name) %> is now in the database.\n";
contents += " <a href=\"#\" class=\"close-modal\">Close this window</a> and use\n";
contents += " the standard search to add the author to the current record.</p>\n";

$('#modal-receiver').append( contents );

$('a.close-modal').click(
  function(){
    $('#modal-receiver').fadeOut('slow');
    $('#blackout').fadeOut('slow');
  });