config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books do
    resources :readings
  end

  resources :authors, :authorships, :genres, :languages, :locations

  root to: 'books#index'

  match 'unread' => 'books#unread', :via => 'get'

  match 'lchart' => 'languages#languageschart', :via => 'get'
end

app/models/book.rb
# frozen_string_literal: true

# Included in the book model is the logic around counting of books
# and stats related to publishers, languages, most-represented authors
class Book < ApplicationRecord
  attr_reader :author_tokens, :author_first, :author_last
  # relationships/associations
  has_many :authorships
  has_many :authors, through: :authorships
  has_many :readings
  belongs_to :language
  belongs_to :genre
  belongs_to :location
  accepts_nested_attributes_for :authors, :authorships
  # validations
  before_save :set_sortby_title

  # Why are all of these abstract methods, and is that overcomplicating this,
  # causing more problems than it solves?

  def self.count_unread
    unreadjoins = <<-SQL
    left join readings r on r.book_id = books.id
    left join genres g on books.genre_id = g.id
    left join locations l on l.id = books.location_id
    SQL
    whereclause = <<-WC
    r.id is NULL and excluded = 0 and g.readable = 1 and l.readable = 1
    WC
    Book.joins(unreadjoins).where(whereclause).count
  end

  def self.find_in_process
    # rewriting this is out of scope just for 4.x upgrade
    # Not as Database agnostic as I'd like
    whereclause = <<-WC
    readings.date_started is not null
    and readings.date_finished is null
    WC
    Book.joins(:readings).where(whereclause)
  end

  def self.find_most_prominent_publishers
    # TODO: rewrite this method to use ORM DSL for better database abstraction
    query = <<-SQL
    select count(publisher) as "total", publisher
    from books
    where publisher <> ""
    group by publisher
    order by total desc
    limit 10;
    SQL
    Book.find_by_sql(query)
  end

  def self.unread_books
    # TODO: rewrite this method to use ORM DSL for better database abstraction
    query = <<-SQL
    select b.id, b.title
    from books b
    Left join readings r on r.book_id = b.id
    Left Join genres g on b.genre_id = g.id
    Left Join locations l on l.id = b.location_id
    where r.id is NULL and b.excluded = 0 and g.readable = 1
    and l.readable = 1 order by b.sortby_title
    SQL
    Book.find_by_sql(query)
  end

  def self.latest_readings
    # TODO: rewrite this method to use ORM DSL for better database abstraction
    query = <<-SQL
    select b.id, b.title, r.date_finished
    from books b
    INNER JOIN readings r on b.id = r.book_id
    where r.date_finished >= DATE_SUB(now(), interval 1 year)
    order by r.date_finished DESC
    SQL
    Book.find_by_sql(query)
  end

  def self.low_hanging_fruit
    # What is low_hanging_fruit? Shorter books which are haven't been read yet
    # Books with no readings, where the location is not something like sold
    # and genre, etc. doesn't exclude it (e.g. Dictionaries)

    # TODO: rewrite this method to use ORM DSL for better database abstraction
    query = <<-SQL
    select b.id, b.title, b.pages 
    from books 
    b Left outer join readings r 
    on r.book_id = b.id
    inner join locations l 
    on l.id = b.location_id and l.readable = 1
    inner join genres g
    on g.id = b.genre_id and g.readable = 1
    where r.book_id is null 
    and b.pages <> 0
    and b.excluded = 0 
    order by pages ASC limit 20;
    SQL
    Book.find_by_sql(query)
  end

  def author_tokens=(ids)
    self.author_ids = ids.split(',')
  end

  def self.search(query)
    # double-check if this is sql-injection proof...
    # according to http://gavinmiller.io/2015/fixing-sql-injection-vulnerabilities/
    # this should be sql-injection safe:
    where('title like ?', "%#{query}%")
  end

  def set_sortby_title
    # as we discover more articles (for instance french, spanish, etc.), add
    # to the array of articles. Ideally, "The Rise and Fall of the Third
    # Reich" returns "Rise and Fall of the Third Reich", "Die Elixiere des
    # Teufels" should return "Elixiere des Teufels"
    # Question: so the first element in the replacement array will replace
    # multiple throughout the title. WHY?
    # Following replaces all instances of the first (and only the first
    # member) of the articles array:
    # self.sortby_title = title.gsub(/#{articles.join('\b|\A')}/i,'').lstrip()

    articles = %w[the a an der die das dem den des ein eine eines einen einer]

    self.sortby_title = title.sub(/#{articles.join('\b|\A')}/i, '').lstrip
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  # GET /books
  # GET /books.xml
  def index
    @page_title = 'Welcome'

    @results = Book.search(params[:search]).order('title') if params[:search]

    # @books = Book.find_all_by_location_id(7)
    @books = Book.find_in_process
    @unread = Book.count_unread
    @prolific_publishers = Book.find_most_prominent_publishers
    @last_read = Book.latest_readings
    @prolific_authors = Author.find_most_prominent_authors
    @lchart = Language.lchartstats

    respond_to do |format|
      format.html
      format.xml  { render xml: @books }
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.xml
  def show
    @book = Book.find(params[:id])
    @page_title = @book.title

    respond_to do |format|
      format.html
      format.xml { render xml: @book }
    end
  end

  # GET /books/new
  # GET /books/new.xml
  def new
    @book = Book.new

    respond_to do |format|
      format.html
      format.xml { render xml: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
    @page_title = 'Editing ' + @book.title
  end

  # POST /books
  # POST /books.xml
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        flash[:notice] = 'Book was successfully created.'
        format.html { redirect_to(@book) }
        format.xml  { render xml: @book, status: :created, location: @book }
      else
        flash[:notice] = "Something's gone horribly wrong."
        format.html { render action: 'new' }
        format.xml  { render xml: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.xml
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update(book_params)
        flash[:notice] = 'Book was successfully updated.'
        format.html { redirect_to(@book) }
        format.xml  { head :ok }
      else
        flash[:notice] = "Something's gone horribly wrong."
        format.html { render action: 'edit' }
        format.xml  { render xml: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.xml
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to(books_url) }
      format.xml  { head :ok }
    end
  end

  def unread
    @books = Book.unread_books
    @fruit = Book.low_hanging_fruit
    @page_title = 'Unread Books'
    respond_to do |format|
      format.html
      format.xml  { render xml: @books }
      format.json { render json: @books }
    end
  end

  private

  def book_params
    params.require(:book).permit(
      { author: %i[author_first author_last] },
      { authorship: %i[contributor editor translator] },
      :author_tokens,
      :title,
      :publisher,
      :ISBN,
      :genre_id,
      :location_id,
      :pages,
      :language_id,
      :notes,
      :excluded,
      :original_language
    )
  end
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
end

app/views/books/_book.haml
- form_for @book do |f|
  - f.error_messages
  - f.fields_for :authors do |author|
    %p
      = author.label :author_first
      = author.text_field :author_first
      = author.label :author_last
      = author.text_field :author_last
  %p
    = f.label :title
    = f.text_field :title
  %p  
    = f.label :publisher
    = f.text_field :publisher
  %p
    = f.label :ISBN
    = f.text_field :ISBN
  %p
    = f.label :pages
    = f.text_field :pages
  %p
    =f.label :language
    =f.select(:language_id, Language.all.collect {|l| [l.Language, l.id]})
  %p
    =f.label :genre
    =f.select(:genre_id, Genre.all.collect{|g| [g.genre, g.id]})
  %p
    =f.label :location, "Current Location: "
    =f.select(:location_id, Location.all.collect{|loc| [loc.Location, loc.id]})
  %p
    =f.label :notes
    =f.text_area :notes
  %p
    =f.submit

app/views/books/_book.html.haml
= form_for @book do |f|
  %p #{ f.label :author_tokens, "Authors"} #{f.text_field :author_tokens, "data-pre" => @book.authors.map(&:json_attributes).to_json }
  %p Need an author which is not found above? #{ link_to "Click here", new_author_path, :remote => true, :class =>"open-modal" }
  
  %p #{ f.label :title , "Title:"} #{ f.text_field :title }
  
  %p #{ f.label :publisher, "Publisher:" } #{ f.text_field :publisher } 
  
  %p #{ f.label :ISBN, "ISBN:"} #{f.text_field :ISBN}
  
  %p #{ f.label :pages, "Pages:"} #{f.text_field :pages}
  
  %p #{ f.label :language, "Language:"} #{f.select(:language_id, Language.all.collect {|l| [l.name, l.id]})}
  
  -# next line really acting up -- 'TypeMismatch expecting Language, got string on submit.'
  -# %p #{ f.label :original_languge, "Original Language"} #{f.select(:original_language, Language.all.sort!{|a,b| a.Language <=> b.Language}.collect { |ol| [ol.Language, ol.id]}, {:default => 0 })}
  
  %p #{ f.label :original_languge, "Original Language:"} #{f.select(:original_language, Language.all.collect { |ol| [ol.name, ol.id]}, :default => 0)}

  %p #{ f.label :genre, "Genre:"} #{f.select(:genre_id, Genre.all.sort{|a,b| a.name <=> b.name}.collect{|g| [g.name.downcase.gsub(/\b\w/){$&.upcase}, g.id]})}
  
  %p #{ f.label :location, "Current Location: "} #{f.select(:location_id, Location.all.sort{|a,b| a.name <=> b.name}.collect{|loc| [loc.name, loc.id]})}
  
  %p #{ f.label :notes, "Notes:"}<br />#{f.text_area :notes}
  
  %p.exclude #{f.check_box :excluded} #{ f.label :excluded, "Exclude from aggregate data (read counts, rating averages, etc.)"}
  
  %p #{ f.submit :class => 'btn btn-large primary'}

app/views/books/edit.haml
%h1 Editing book

-form_for @book do |f|
  -f.error_messages
  %p
    =f.label :title
    =f.text_field :title
  %p
    =f.label :publisher
    =f.text_field :publisher
  %p
    =f.label :ISBN, 'ISBN:'
    =f.text_field :ISBN
  %p
    =f.label :language
    =f.select(:language_id, Language.all.collect {|p| [p.Language, p.id]})
  %p
    =f.label :genre
    =f.select(:genre_id, Genre.all.collect{|g| [g.genre, g.id]})
  %p
    =f.label :location, "Current Location: "
    =f.select(:location_id, Location.all.collect{|loc| [loc.Location, loc.id]})

  %p
    =f.label :notes
    =f.text_area :notes
  %p
    =f.submit 'Submit Changes'

%p
  =link_to 'Show', @book 
  |
  =link_to 'Back to Main index', books_path

app/views/books/edit.html.haml
%h1 Editing book
%h4 (Currently known as <i>#{@book.title}</i>)

-# Refer to http://guides.rubyonrails.org/active_record_validations_callbacks.html#working-with-validation-errors
-# This next line causes raw output of {}
-# =@book.errors

=render 'book'

%p #{ link_to 'Cancel Edits', @book } | #{ link_to 'Back to Main index', books_path }

app/views/books/index.haml
%h1 Welcome to the Bibliophile library catalog.

%p here's a quick glimpse of what's being reported as currently being read right now.

-@books.each do |book|
	.item
		%h3.title=link_to book.title, book
		-book.authorships.each do |a|
			%p= link_to a.author.fullname, author_path(a.author)
		.links
			%span= link_to 'Show', book
			%span= link_to 'Edit', edit_book_path(book)

-if @unread > 0
	%p #{@unread} books are reported unread.

%a= link_to 'New book', new_book_path

app/views/books/index.html.haml
%h1 Welcome to the Bibliophile library catalog.

-if @results
	%h2 Search Results by Title
	%ul
		-@results.each do |b|
			%li
				=link_to b.title, b

%p here's a quick glimpse of what's being reported as currently being read right now.

-@books.each do |book|
	.item
		%h3.title=link_to book.title, book
		-book.authorships.each do |a|
			%p= link_to a.author.fullname, author_path(a.author)
		.links
			%span= link_to 'Show', book
			%span= link_to 'Edit', edit_book_path(book)

%p= link_to 'New book', new_book_path
#unread_prompt
	-if @unread > 0
		%p #{@unread} books are reported #{ link_to 'unread', unread_path }.


#administrivia
	-if @prolific_publishers
		#prolific_publishers
			%h3 Most Represented Publishers
			%table
				%tr
					%th Publisher
					%th Books
				- @prolific_publishers.each do |pub|
					%tr
						%td #{pub.publisher}
						%td #{pub.total} 
	
	-if @last_read
		#last_read
			%h3 Latest Read Books:
			%p #{@last_read.count} books completed in the last 12 months:
			%ol
			-@last_read.each do |read|
				%li
					%h5=link_to read.title, read
					%p.small Completed #{read.date_finished.strftime('%B %-d, %Y')}
	
	-if @prolific_authors
		#prolific_authors
			%h3 Most Represented Authors:
			-@prolific_authors.each do |author|
				%h5=link_to author.name, author
				%p.small Number of Titles: #{author.total}
#charts
	-if @lchart
		%h3 Books By Original Language:
		#lchart
			

app/views/books/new.haml
%h1 New Book
- form_for @book do |f|
  - f.fields_for :authors do |author|
    %p
      = author.label :author_first
      = author.text_field :author_first
      = author.label :author_last
      = author.text_field :author_last
  %p
    = f.label :title, "Title: "
    = f.text_field :title
  %p  
    = f.label :publisher, "Publisher: "
    = f.text_field :publisher
  %p
    = f.label :ISBN, "ISBN: "
    = f.text_field :ISBN
  %p
    = f.label :pages, "Pages: "
    = f.text_field :pages
  %p
    =f.label :language, "Language: "
    =f.select(:language_id, Language.all.collect {|l| [l.Language, l.id]})
  %p
    =f.label :genre, "Genre: "
    =f.select(:genre_id, Genre.all.collect{|g| [g.genre, g.id]})
  %p
    =f.label :location, "Current Location: "
    =f.select(:location_id, Location.all.collect{|loc| [loc.Location, loc.id]})
  %p
    =f.label :notes
    =f.text_area :notes
  %p
    =f.submit

%p= link_to 'Back', books_path

app/views/books/new.html.haml
%h1 New Book
=render 'book'
%p= link_to 'Back', books_path

app/views/books/show.haml
%h2= @book.title
- @contributors = []
- @book.authorships.each do |a|
  -if a.translator?
    %h4= link_to a.author.fullname + ", translator", author_path(a.author)
  -elsif a.editor?
    %h4= link_to a.author.fullname + ", editor", author_path(a.author)
  -elsif a.contributor?
    -@contributors << a
  -else
    %h3= link_to a.author.fullname, author_path(a.author)

- if @contributors.length > 0
  #contributors
    %h3 Contributors:
    -@contributors.each do |c|
      %h4= link_to c.author.fullname, author_path(c.author)

%p Publisher: #{@book.publisher}

%p Notes: #{@book.notes}
  
%p ISBN: #{@book.ISBN}

%p Pages: #{@book.pages}

%p Current Location: #{@book.location.Location}

%p Genre: #{ @book.genre.genre.downcase.gsub(/\b\w/){$&.upcase} }

%p Language: #{@book.language.Language}

%p Last Modified: #{@book.updated_at}

-if @book.readings
  = render 'readings/show'
%p #{ link_to 'Add a reading for this book', new_book_reading_path( @book )}
%p #{link_to 'Edit', edit_book_path(@book)} | #{link_to 'Back', books_path }

app/views/books/show.html.haml
.page-header
  %h1 <i>#{@book.title}</i>
- @contributors = []
- @book.authorships.each do |a|
  -if a.translator?
    %h4= link_to a.author.name + ", translator", author_path(a.author)
  -elsif a.editor?
    %h4= link_to a.author.name + ", editor", author_path(a.author)
  -elsif a.contributor?
    -@contributors << a
  -else
    %h3
      #{link_to a.author.name, author_path(a.author)}
      %span.small #{link_to 'Edit this relationship', edit_authorship_path(a.id)}

- if @contributors.length > 0
  #contributors
    %h3 Contributors:
    -@contributors.each do |c|
      %h4= link_to c.author.name, author_path(c.author)

%p 
  %strong Publisher:
  #{@book.publisher}

%p 
  %strong Notes:
#{markdown_parse(@book.notes)}
  
%p
  %strong ISBN:
  #{@book.ISBN}

%p
  %strong Pages:
  #{@book.pages}

%p
  %strong Current Location:
  #{@book.location.name}

%p
  %strong Genre:
  #{ @book.genre.name.downcase.gsub(/\b\w/){$&.upcase} }

%p
  %strong Language:
  #{@book.language.name} 

-# #{@book.original_language.name} will not work, since there's no original_
-# language method. Look into what to do translate this into a usable string
-# maybe what is used for the pie-graph on the front page could be helpful
%p
  %strong Original Language:
  #{Language.find(@book.original_language).name}

%p 
  %strong Last Modified:
  #{@book.updated_at}

%p #{link_to 'Edit', edit_book_path(@book)} | #{link_to 'Back', books_path }

-if @book.readings
  = render 'readings/show'

%p #{ link_to 'Add a reading for this book', new_book_reading_path( @book )} | #{ link_to 'Show unread books', unread_path }

app/views/books/unread.html.haml
%h1 Unread Books

%h2 Low-Hanging Fruit
%p books which have relatively low page counts, but haven't yet been read. If you're looking for Thomas Mann or James Joyce, look elsewhere.

%table
	-@fruit.each do |book|
		%tr
			%td #{book.title}
			%td #{book.pages}
			%td= link_to 'Show', book
			%td= link_to 'Edit', edit_book_path(book)


%p What classifies a book as "unread?" In general, it's a book that is in the catalog which has no associated reading.

%table
	-@books.each do |book|
		%tr
			%td #{book.title}
			%td= link_to 'Show', book
			%td= link_to 'Edit', edit_book_path(book)