config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books do
    resources :readings
  end

  resources :authors, :authorships, :genres, :languages, :locations

  root to: 'books#index'

  match 'unread' => 'books#unread', :via => 'get'

  match 'lchart' => 'languages#languageschart', :via => 'get'
end

app/models/location.rb
# frozen_string_literal: true

# Basic Active Record class.
# No business logic here as yet.
class Location < ApplicationRecord
  has_many :books
end

app/controllers/locations_controller.rb
# frozen_string_literal: true

class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.xml
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.xml
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render xml: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.xml
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render xml: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.xml
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to(@location, notice: 'Location was successfully created.') }
        format.xml  { render xml: @location, status: :created, location: @location }
      else
        format.html { render action: 'new' }
        format.xml  { render xml: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.xml
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to(@location, notice: 'Location was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render action: 'edit' }
        format.xml  { render xml: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.xml
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to(locations_url) }
      format.xml  { head :ok }
    end
  end

  private

  def location_params
    params.require(:location).permit(
      :name,
      :readable
    )
  end
end

app/helpers/locations_helper.rb
# frozen_string_literal: true

module LocationsHelper
end

app/views/locations/edit.html.haml
%h1 Editing location

= form_for @location do |f|
  %p #{f.label :name, "Location Name: "}#{ f.text_field :name }
  %p #{f.check_box :readable} #{ f.label :readable, "If a book is in this location, can it still be read (if it hasn't)? For example, if it was returned to the library? Sold?"}
  %p #{f.submit}

%p #{ link_to 'Show', @location } | #{ link_to 'Back', locations_path }

app/views/locations/index.html.haml
%h1 Listing locations

%table
	-@locations.each do |location|
		%tr
			%td #{location.name}
			%td=link_to 'Show', location
			%td=link_to 'Edit', edit_location_path(location)
			%td=link_to 'Destroy', location, :confirm => 'Are you sure?', :method => :delete

%a=link_to 'New location', new_location_path

app/views/locations/new.html.haml
%h1 New Location

= form_for @location do |f|
  %p #{f.label :name, "Location Name: "}#{ f.text_field :name }
  %p #{f.check_box :readable} #{ f.label :readable, "If a book is in this location, can it still be read (if it hasn't)? For example, if it was returned to the library? Sold?"}
  %p.clearfix #{f.submit}

app/views/locations/show.html.haml
.page-header
  %h1 #{ @location.name}

  -if @location.readable?
    %p This book is in a readable location

%div#book-list
  %h3 Books in this location:
  %ul
  -@location.books.each do |book|
    %li= link_to book.title, book_path(book)

%p #{ link_to 'Edit', edit_location_path(@location) } | #{ link_to 'Back', locations_path }